# Generated by Django 2.1.1 on 2020-07-13 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='name')),
                ('value', models.DecimalField(decimal_places=1, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(99999.9)], verbose_name='value')),
                ('discount_value', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(99999.9)], verbose_name='discount value')),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1)], verbose_name='stock')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
